### ISSUE TITLE
hash data using FNV potential false positive

### ISSUE THREAD

**Issue by edeca** [fireeye/capa-rules#108]
## Summary

The default rule `hash data using FNV` appears to generate a false positive for a string encoding routine.

## Examples

Minimal repro - single function extracted, needs to be turned into a function with `p` in IDA:

`558BEC5153565768001000008BF88BF1E8BBF4FFFF8365FC008BD80FB6470166C1E008590FB60F0FB7C00BC183C7028BCB2BFB8A140F32D088118BD069C0000094BFC1EA1069D26C401B692BC233D22D413B68463811740DFF45FC41817DFCFA0F00007CCE53891689560489560889560CE847FEFFFF53E82BF4FFFF595F8BC65E5BC9C3
`
## Possible improvements

The top level constants for 32 bit and 64 bit FNV primes appear to be ignored. They are not present in this function, and the `or` branch is empty in capa explorer.

## Additional context

* [Example detection inside capa explorer](https://imgur.com/a/zC0C1d6)
* [Screenshot of the code which is detected](https://imgur.com/a/jSiVXua)

**Comment by mr-tz** [comment]
First off, I love how you provided that minimal example. We should use that more moving forward; potentially also for our tests!

Thanks for the find and the detailed FP report.

In #109 I provided a fix. The issue was the `optional` block under the `or` which always results in a true for the block looking for the constants.
